on:
  workflow_dispatch:

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.8
        with:
          verbose: 1
          max-size: "760M"
      - name: update
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install libgmp-dev libmpfr-dev libmpc-dev libisl-dev flex bison texinfo autoconf libtool libzstd-dev zlib1g-dev
      - name: pre
        run: ./pre.sh
      - name: env data
        run: |
          thetag=$(cat tag)
          therev=$(cat rev)
          echo "my_tag=$thetag" >> $GITHUB_ENV
          echo "my_rev<<_$thetag_" >> $GITHUB_ENV
          echo "$therev" >> $GITHUB_ENV
          echo "_$thetag_" >> $GITHUB_ENV
      - name: build64
        run: ./build64.sh
      - name: build32
        run: ./build32.sh
      - name: pack
        run: ./pack.sh
      - name: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./mingw-gcc
      - name: release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ./mingw-gcc.tgz
          body: ${{ env.my_rev }}
          commit: main
          makeLatest: true
          name: build_${{ env.my_tag }}
          tag: ${{ env.my_tag }}
